### ISSUE TITLE
GCS install - consistent caps in Roles & privileges

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#101]
For this bullet:  The creator of the endpoint is granted administrator role by default

I think it should be Administrator role to be consistent with other usage in the section.

There are other occurrences of "administrator" that aren't followed by "role" - not sure if those should be cap or not.

**Comment by danpowers** [comment]
>There are other occurrences of "administrator" that aren't followed by "role" - not sure if those should be cap or not.

When you're looking at these various 'administrators' I think it's important to distinguish between system/server/network administrators and those who have been granted the Administrator Role for a given endpoint definition. It probably makes sense to capitalize the Endpoint Administrator Role, but the other instances of administrator probably shouldn't be capitalized. It's entirely possible that one person could be an administrator in more than one sense. I think we really only want to use caps to distinguish the Administrator Role for endpoints from the other administrator functions/capacities a person may function in.
