### ISSUE TITLE
Update screenshots and documentation with regards to the "share" and "permissions" buttons in the Transfer Files interface

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/docs.globus.org#110]
These options have moved from the hamburger menu to be a toplevel button above the directory listing.

I see at least the following:

- https://docs.globus.org/how-to/share-files/
- https://docs.globus.org/faq/transfer-sharing/

**Comment by teresas** [comment]
@corpulentcoffee I've updated the screenshots on staging http://docs.staging.globuscs.info/. Take a look and let me know if they're good for prod.

**Comment by corpulentcoffee** [comment]
(copying my note from https://github.com/globusonline/webapp-ember/issues/946#issuecomment-289879591)

I looked at the new "share" button / Roles stuff on /how-to/share-files/ and also the minor changes to /faq/transfer-sharing/ and they look OK to me.

If you want to be in-sync with us going to production with the changes, we'll be doing it Wednesday around 10:30 AM.
