### ISSUE TITLE
Screenshots of webapp in "How To Link a New Identity to an Existing Globus Account" outdated

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/docs.globus.org#118]
The screenshots for Step 1 and Step 5 of "How To Link a New Identity to an Existing Globus Account" (https://docs.globus.org/how-to/link-to-existing/) are outdated since the webapp's Account page got stripped down.

Arguably, at this point, these instructions could be rewritten to have users use Auth directly (via https://auth.globus.org/identities) instead of going through the webapp... this may be desirable anyway given that the webapp's Account page doesn't have much information on it anymore.

**Comment by teresas** [comment]
@ranantha Are these instructions something we want to change to use Auth directly as @corpulentcoffee mentioned above?

**Comment by mattias-lidman** [comment]
Pointing users straight to Auth makes sense to me, especially if the webapp's Account page is eventually going away as discussed.

**Comment by ranantha** [comment]
I suggest we update the screenshots, but leave this as something the user starts from the webapp rather than directly going to Auth - starting with that link is more accessible for a user than remembering the direct link to Auth.

**Comment by teresas** [comment]
I can keep them the same. When running through the flow, I didn't hit the second screen in step 3 or step 4 at all. Has this been streamlined or changed? Or is it maybe because the demodoc user had the account linked before and I had to remove it in order to relink it for the screenshots?

**Comment by corpulentcoffee** [comment]
I don't know if you need to re-capture those screens (neither are in the webapp), *but if you do*, I believe you can

- remove access to Globus at https://myaccount.google.com/permissions to get the screen from Step 3 again
- unlink the accounts at https://auth.globus.org/identities to get the screen from Step 4 again (linking an identity that is already linked is an automatic success now: globusonline/globus-auth#976)

**Comment by teresas** [comment]
@corpulentcoffee I didn't think I needed to re-capture those screens but just wanted to make sure they were still in the flow. I did update the images mentioned on [staging](http://docs.staging.globuscs.info/how-to/link-to-existing/). Take a look and let me know if they're good for prod.

**Comment by corpulentcoffee** [comment]
The new screenshots look good, thanks!
