### ISSUE TITLE
"How to Share Data Using Globus" needs update

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#147]
Item 3 in this document says...
... If the "share" option is not enabled, the endpoint is not configured for sharing.

This is not true -- you don't find out until after step 4, after you click "Create", if you are unable to share.      Asked about this in slack support group, and confirmed the behavior changed over time.    

Recommend just deleting the "If the 'share'..." sentence to make document correct.     

Perhaps later, add section w/ the various error messages you get if endpoint not configured for sharing, user can't share, or path not sharable.

**Comment by teresas** [comment]
Removed line for now.
