### ISSUE TITLE
Update globus-connect-server-installation-guide Package Download Links

### ISSUE THREAD

**Issue by sirosen** [globusonline/docs.globus.org#152]
The current Globus Connect Server install doc includes URIs for files in `http://toolkit.globus.org/ftppub/globus-connect-server/`.
We should update these to the relevant `https://downloads.globus.org/toolkit/globus-connect-server/` locations, as this is the new package repository.

I've also asked Joe to add a redirect to the current site, but it would be best to get the new name directly into people's scripts and such.

For example,
```
http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo_latest_all.deb
  ||
  VV
https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo_latest_all.deb
```

EDIT: fixed a typo which made the new download location invalid.

**Comment by danpowers** [comment]
Hi Stephen,

I noticed that 'https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server/RPM-GPG-KEY-Globus' seems to be missing.

```
# rpm --import https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server/RPM-GPG-KEY-Globus
curl: (22) The requested URL returned error: 404 Not Found
error: https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server/RPM-GPG-KEY-Globus: import read failed(2).
```

This key is referenced by our install instructions as 'http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus'. Would you or Joe be the right person to ask about making that file available?

**Comment by sirosen** [comment]
I think we need @bester's help on that.
Looks like there are missing files necessary for the install process?

I'm happy to copy them from the older location manually, but I don't want to do that and hide an underlying problem.

**Comment by teresas** [comment]
We might also need to look at https://docs.globus.org/globus-connect-server-v5-installation-guide/ to replace the urls

**Comment by danpowers** [comment]
Heard back from Joe on this.

He said the correct URL for the RPM-GPG-KEY-Globus should be:

https://downloads.globus.org/toolkit/gt6/stable/repo/rpm/RPM-GPG-KEY-Globus

I've confirmed this works.

**Comment by danpowers** [comment]
Hi Teresa,

I've updated the URLs in section 3.1 of the GCS Install Guide and pushed the changes into the i152 feature branch. I'm still not able to push to staging, as I still get the S3 'AccessDenied' error when running the 'make staging' command. I'd appreciate it if you could give the i152 branch a look and push it to staging when you feel that's appropriate.

**Comment by teresas** [comment]
@danpowers Pushed to staging. Check and see if it's good for prod.

**Comment by danpowers** [comment]
@teresas Looks good. Thanks.
