### ISSUE TITLE
Remove redirect links on auth reference page

### ISSUE THREAD

**Issue by teresas** [globusonline/docs.globus.org#16]
In section 5.1 (maybe elsewhere also, I haven’t checked), the links to RFC 7662 and other external docs are:

https://www.google.com/url?q=https://tools.ietf.org/html/rfc7662&sa=D&ust=1459362629167000&usg=AFQjCNE4XOZ2Si4HXEsT5HWm_bwUCVKuhw

update all links so not going through google

**Comment by teresas** [comment]
doing find/replace to fix google.com/url? redirects

404s that also need to be fixed:
- 3.2, the last two links
- 3.3.1, second paragraph https://auth.globus.org/v2/oauth2/token
- 4.2 https://auth.globus.org
- 5.1 3rd paragraph W3C.REC-html5-20141028
- 5.2 3rd paragraph W3C.REC-html5-20141028
- 6. All links

odd link:
3.6 third bullet point link is broken in 2 pieces; not sure of the intention

**Comment by bjmc** [comment]
> - 3.2, the last two links

Probably shouldn't be clickable links at all. These are the Globus Auth endpoints

- 3.3.1, second paragraph https://auth.globus.org/v2/oauth2/token

> Same as above.

- 4.2 https://auth.globus.org

> Ditto. Maybe we should make auth.globus.org redirect to the homepage, or link to the docs or something?

- 5.1 3rd paragraph W3C.REC-html5-20141028

Link target should be https://www.w3.org/TR/2014/REC-html5-20141028/iana.html#application/x-www-form-urlencoded text can be "W3C recommendations"

- 5.2 3rd paragraph W3C.REC-html5-20141028

> Same as above

- 6. All links

I'd say just remove all of section 6, unless we're trying to look academic. If we want to keep it, those links can just resolve to their text, e.g. <http://www.rfc-editor.org/info/rfc7231>. points to http://www.rfc-editor.org/info/rfc7231

**Comment by teresas** [comment]
pieced link in 3.6 (mentioned above) should also not be clickable
