### ISSUE TITLE
Update IdP FAQ

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#161]
We've decided to no longer require the full Research & Scholarship attributes for adding CILogon IdPs, as described here:

https://docs.globus.org/faq/security/#how_do_i_get_my_organization_added_as_an_option_to_log_into_globus

Going forward, we will only require ePPN (eduPersonPrincipalName) and ePTID (eduPersonTargetedID). This only applies to IdPs requesting to be added manually -- we can't tell programmatically if an IdP supports these attributes if they don't support R&S, so in these cases the IdP administrators will need to contact support to get added.

Can you update this FAQ entry to reflect these changes please?

**Comment by danpowers** [comment]
@teresas I've got these changes ready in the i161 branch, but I still can't run the 'make stating' command due to the S3 error discussed before. Can you take a look and push to staging if you deem it ready?

**Comment by teresas** [comment]
@danpowers Staging should be updated. Let me know if it's good for prod.

**Comment by danpowers** [comment]
@teresas Looks good. Thank you.
