### ISSUE TITLE
Edit 3.1.1 in the GCS Install Guide

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#163]
Edit 3.1.1 in the GCS Install Guide to make clear that EPEL repo is a dependency for GCS on RHEL variants.

https://docs.globus.org/globus-connect-server-installation-guide/#install_section

**Comment by danpowers** [comment]
@teresas Can you take a look at branch i163 and push to staging when you feel appropriate. I still can't run 'make staging' as I still get the S3 (AccessDenied) error when attempting to do so. Thanks.

**Comment by teresas** [comment]
@danpowers I ran 'make staging', so the changes should be up to review. Take a look and let me know if it's good for prod. @sirosen Can you take a look at the permissions issue again and give Dan the ability to run the scripts?

**Comment by danpowers** [comment]
@teresas Everything looks good. Thanks.
