### ISSUE TITLE
Update GCSv5/Google Drive doc

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#164]
Update GCSv5/Google Drive doc per Joe and Rachana to reflect changes in the new packages:

https://docs.globus.org/premium-storage-connectors/google-drive/

**Comment by danpowers** [comment]
@teresas I've got these changes in i164 ready to go. Please take a look and push to staging when you feel appropriate.

**Comment by teresas** [comment]
@danpowers I've run the make script for staging. Take a look and let me know if it's good for prod.

**Comment by danpowers** [comment]
@teresas Everything looks good. Thanks.
