### ISSUE TITLE
Additional GCSv5 Doc updates per Rachana

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#166]
Additional GCSv5 Doc updates per Rachana:

https://docs.google.com/document/d/1I-sk5SaqIwZf7AemLnYtQtLW1bNoJ9jldvsLvqc8Xbk/

**Comment by danpowers** [comment]
@teresas I've got these changes ready for i166. Please review and push to staging when you feel appropriate.

**Comment by teresas** [comment]
@danpowers Just ran the script so staging should be updated. Let me know when it's good for prod.

**Comment by danpowers** [comment]
@teresas Looks good. Thanks.
