### ISSUE TITLE
Additional GCSv5/Google Drive Connector clarifications

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#168]
Additional GCSv5/Google Drive Connector clarifications per Ruth/Rachana's suggestions:

https://docs.google.com/document/d/1I-sk5SaqIwZf7AemLnYtQtLW1bNoJ9jldvsLvqc8Xbk/

**Comment by danpowers** [comment]
@teresas Hi Teresa. I've got a couple of additional changes ready in i168. Please have a look and push to staging and prod when you feel appropriate. I'll be on vacation tomorrow (Friday), so you might need Rachana or Joe to give the staging doc a look before pushing to prod? Thanks.

**Comment by teresas** [comment]
@danpowers Running the script now; should be up in a few. Enjoy your vacation! @ranantha Maybe one of you could take a look and let me know if that's good for prod?

**Comment by danpowers** [comment]
@teresas Looks good to me. Thanks.

@ranantha I stepped through the 'Prepare a Google project for use with Globus' section again while looking at the doc on staging, and I think the change there should address the problem Ruth experienced. Another rough spot she had was step 8 in the 'Globus Connect Server v5 Install Instructions' section, which could maybe be smoothed out a bit.

One other thing that might be an issue would be to make sure that httpd is properly started when running 'globus-connect-server-setup' the first time after doing the GCS install. There was an issue with that not happening earlier on, but I don't think that's still a problem. If it is, then it's resolved by simply manually starting httpd for the first time after the GCS install. If you hit that issue in your test install tomorrow, then we'll want to update the doc to make sure to include a step to manually start httpd the first time or will want to ask Joe to make sure that the install/setup process handles it.

**Comment by ruthaydt** [comment]
Dan  — thanks for all the help you gave me yesterday, and for making changes to address some of the bumps I ran into before your vacation.

Others — 

I’ll look at the docs.globus.org <http://docs.globus.org/> version and integrate those changes into the other ones I’m suggestion (currently gathering in google doc Rachana started).  

I think there are a few edits that need to be made on the live version, even if the more extensive one I’ll be suggesting aren’t adopted.   I’m not going to focus on those separately as I want to try and get through a successful install today, but will make my recommended changes in the doc I’m working on.   If someone else wants to address in the meantime, one that caught my eye was  the first Important box that says to verify you GCSv5 endpoint is functional before you move to configure Google Drive Connector should be removed or made clearer.   Later we tell the reader that this version only works with google Drive Connector so how can I verify functionality in advance of that install?       

—Ruth
