### ISSUE TITLE
Update FAQ regarding mapping to a network drive

### ISSUE THREAD

**Issue by rohder** [globusonline/docs.globus.org#170]
Please update the following FAQ - https://docs.globus.org/faq/globus-connect-endpoints/#what_happens_if_my_user_profile_is_on_a_network_share 

Replace these links - 
http://windows.microsoft.com/en-us/windows/create-shortcut-map-network-drive 
http://windows.microsoft.com/en-us/windows-8/create-shortcut-to-map-network-drive 

with - 
 https://support.microsoft.com/en-us/help/4026635/windows-map-a-network-drive

**Comment by danpowers** [comment]
@teresas I've got the changes in i170 ready. Please have a look and push to staging when you feel appropriate.

**Comment by teresas** [comment]
@danpowers I'm running the script now; your updates should be on staging in a few.

**Comment by danpowers** [comment]
@teresas I just checked the updated FAQ on staging and it looks good to me. Thanks.
