### ISSUE TITLE
Google drive connecter guide - and link to user howto

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#174]
In the Google Drive Connector document on staging the sentence 
"The endpoint is now ready for users to login and access content on Google Drive." 
appears near the end of the "Configure endpoint to use the Google Drive Connector" section (right before the Note)

Please add some words/link to the "How to Access your Google Drive with Globus" page.  http://docs.staging.globuscs.info/how-to/access-google-drive/

Maybe a new sentence "User documentation is available at http://docs.staging.globuscs.info/how-to/access-google-drive/", or whatever fits the general style of the overall docs.

**Comment by ruthaydt** [comment]
Change "how to" to upper case "How To" so that it's consistent with capitalization used in document intro & with the "How To" in the menu bar.    

Looks good other than that.

**Comment by teresas** [comment]
@ruthaydt This has been updated on staging. I also took the word "this" out of the link so that it was consistent with others. Let me know if this is good for prod, and I'll push this along with #169 and #172.

**Comment by ruthaydt** [comment]
Changes look good to me. thanks
