### ISSUE TITLE
Update GCS + GCP firewall doc

### ISSUE THREAD

**Issue by danpowers** [globusonline/docs.globus.org#179]
Update GCS + GCP firewall doc:

https://docs.globus.org/globus-connect-server-installation-guide/#open-tcp-ports_section

&

https://docs.globus.org/how-to/configure-firewall-gcp/

**Comment by danpowers** [comment]
@teresas I've pushed the i179 branch changes to staging. Please have a look and push to prod when you deem appropriate.

**Comment by teresas** [comment]
Pushed to prod.
