### ISSUE TITLE
Google Drive doc updates

### ISSUE THREAD

**Issue by teresas** [globusonline/docs.globus.org#185]
First section: 
- [x] change "The Google Drive connector requires Globus Connect Server version 5, a new major release of the server that requires a separate install.” to:
"The Google Drive connector requires Globus Connect Server version 5, a new major release of the server that has to be installed on a separate machine from any other Globus Connect Server installations. “ 

Registration of endpoint with Google 
Add one more step at end: 
- [x] "10. Google has a quota on the number of calls that can be made to it’s API. We recommend requesting for an increase in the quota for the Google Drive API to improve performance on data transfers to and from Google Drive. 
(a) Under Google Drive API, choose the “Quotas” tab. 
(b) Choose to edit the “Quries per 100 seconds per user”, and that window provides a link to “apply for higher quota”. 
(c) Using the form you can request for higher API limits per user using the “Explanation section of the form. Following is an example to serve as guidance: 
Requested max Queries per Day: Default setting, no change requested 
Requested peak QPS: 500 
Explanation: We are using Globus (globus.org) for Google Drive and use is limited by the API quota. Please increase the queries per 100 seconds per user to 10,000 and max queries per 100 seconds to 50000. 
You can also provide additional context about your institution. 
Once this request is approved, note the queries per 100 seconds per user value to configure in the endpoint. 

Configuration section, add: 
- [x] 2. If you were approved for a quota increase on the number of queries per 100 seconds per user, under the [Google Drive] section, 
(a) set UserAPIRateQuota to be the number of queries per 100 seconds per user 

Not critical: 
- [x] Would like links to GOogle console and GLobus app registration to open in new tab.

**Comment by ruthaydt** [comment]
Please see one additional request inline...
> On Aug 28, 2017, at 5:30 PM, Teresa <notifications@github.com> wrote:
> 
> First section:
> 
>  "The Google Drive connector requires Globus Connect Server version 5, a new major release of the server that requires a separate install.”
>  "The Google Drive connector requires Globus Connect Server version 5, a new major release of the server that has to be installed on a separate machine from any other Globus Connect Server installations. “
Say “on a separate system” (not on a separate machine) to be consistent with use of ‘system’ rather than ‘machine’ elsewhere.
