### ISSUE TITLE
Update RPG Appendix C

### ISSUE THREAD

**Issue by teresas** [globusonline/docs.globus.org#33]
Per @danpowers 
Currently, Appendix C in the RPG contains the following:

Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
`$ sudo yum update globus-connect-server
`
SuSE Linux Enterprise Server
```
$ sudo zypper refresh
$ sudo zypper update globus-connect-server
```

Debian, Ubuntu
```
$ sudo apt-get update
$ sudo apt-get upgrade globus-connect-server
```

I'd like to update this such that it reads as so:

Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
`$ sudo yum update \*globus\* \*myproxy\* \*gsi-openssh\*
`
SuSE Linux Enterprise Server
```
$ sudo zypper refresh
$ sudo zypper up \*globus\* \*myproxy\* \*gsi-openssh\*
```

Debian, Ubuntu
```
$ sudo apt-get update
$ sudo apt-get install --only-upgrade ".*globus.*" ".*myproxy.*" ".*gsi-openssh.*"
```

**Comment by danpowers** [comment]
Saw the email that was sent for this thread and I think github ate some of the characters / interpreted them as markdown.

Just for clarity/history are the literal values:
```
Red Hat Enterprise Linux, CentOS, Scientific Linux, Fedora
$ sudo yum update \*globus\* \*myproxy\* \*gsi-openssh\*
SuSE Linux Enterprise Server
$ sudo zypper refresh
$ sudo zypper up \*globus\* \*myproxy\* \*gsi-openssh\*
Debian, Ubuntu
$ sudo apt-get update
$ sudo apt-get install --only-upgrade ".*globus.*" ".*myproxy.*" ".*gsi-openssh.*"
```

**Comment by teresas** [comment]
I updated the original comment. Thanks!
