### ISSUE TITLE
Upgrade to Nanoc 4

### ISSUE THREAD

**Issue by teresas** [globusonline/docs.globus.org#34]
- Nanoc 4 brings identifiers with extensions, and thereby solves a long-standing usability issue. It also introduces glob patterns, which makes rules easier to write.
- Nanoc 4 paves the way for new features and performance improvements. Nanoc 3 exposed its internals in a public API, making it hard to make significant changes.
- Nanoc 3 is in maintenance mode, which means it will only get critical bug fixes.

- running into problems with files that have the same name but different extensions; upgrading should fix that issue

**Comment by sirosen** [comment]
I did a bit of work on this, and I determined with 95% certainty that the current blocker is the format of the config file.
It seems that the old config file has an empty element in an array. Nanoc3 could deal, but Nanoc4 chokes on it.
I'm working on fixing it up now.

I'm also working from scratch on the dependencies we should be installing.
I think it's currently `nanoc ~> 4.0` and `nokogiri ~>1.6`, but I'm sure there will be others.

**Comment by sirosen** [comment]
Interesting progress.
Current failures are in the Rules file. That isn't really that surprising, as it hooks directly into Nanoc's inner workings.
What is surprising is the degree to which we felt it necessary to munge things.

@teresas I'm going to focus on just getting it working for now, but I'd like us to do a systematic review of the logic at play there, and maybe cut down on the level of customization. That's a tomorrow issue, unless getting it working is impossible (in which case it will become a today issue).

**Comment by teresas** [comment]
Yeah, I figured the Rules file was probably what was causing it to choke. And I agree that the Rules file is a bit messy and could definitely use a clean up. I think there's also a chance we can clean up some of the layout files since quite a few are pretty much cloned with a single line change; maybe we can somehow pass it a variable and eliminate the extra files. But yes, getting it working is #1, cleaning up the rules file is probably #2, and cleaning up the rest would fall last.
