### ISSUE TITLE
Transfer API doc error: shared endpoint creation doesn't state requirement for `host_endpoint`

### ISSUE THREAD

**Issue by sirosen** [globusonline/docs.globus.org#61]
@corpulentcoffee I'd like you to confirm that I'm not seeing strange behavior, and that this is consistent with your experience with the API.
We state `host_endpoint_id` as a part of Shared Endpoint documents, but if I send one with that, rather than `host_endpoint`, the API gives back

```
HTTP status:      400
request_id:       b8cLb48tQ
code:             BadRequest
message:          Bad JSON Data: Field 'host_endpoint' not found
```

There's a bug here (which I'll file against Transfer) because that field should be translated/respected, but I don't know if that will make it into the current release.
The docs need fixing in the meantime.

I'm still not quite sure where the change is necessary.
Amending the description of a shared endpoint doc seems like poor form, since we're supposed to be _deprecating_ `host_endpoint` as a field.
I think I'll put it in as a warning blob here: https://docs.globus.org/api/transfer/endpoint/#create_shared_endpoint

**Comment by corpulentcoffee** [comment]
Sending `host_endpoint` during the creation but looking at `host_endpoint_id` on reads is consistent with what I know.

**Comment by sirosen** [comment]
I'm going to take a wait-and-see approach on this. If we're fixing this soon in the API to be more accepting, then we shouldn't bother updating the docs. Depending on when it looks like that might happen, I might push to amend the docs to be more accurate before then.
