### ISSUE TITLE
Add endpoint role documentation to RPG

### ISSUE THREAD

**Issue by teresas** [globusonline/docs.globus.org#77]
https://docs.google.com/document/d/1INZY3Fbgt35RjGZgnmbOpK2aPNVqJdnT3JWqYua65lk/edit

**Comment by corpulentcoffee** [comment]
FYI @teresas (in case you already did work on this locally), I just edited the "Access Manager" part in the "Role and privileges" section to fix an inaccuracy.

Instead of:
> Can be granted by any user who has Administrator or Access Manager role on the endpoint. The creator of the endpoint is granted this role by default.

This should read:
> Can be granted by any user who has Administrator role on the endpoint

**Comment by teresas** [comment]
I'll fix. Thanks!
