### ISSUE TITLE
globus-connect-server-installation-guide outdated info

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#93]
See text from manual below.  

Problem: The endpoints go#ep1 and go#ep2 are no longer things you can enter on the screen now that search is enabled.   go#ep1 matches (kind of) Globus Tutorial Endpoint 1, as well as ballen#ep1share.    What should be used in the manual instead of these?  I think probably "Globus Tutorial Endpoint 1" and "Globus Tutorial Endpoint 2".      Also... the go#ep. appears again in 7.1.1 but I didn't cut/paste that part

Manual text:

7.1.1. Test Basic Endpoint Functionality

An important verification of endpoint health is to confirm that the endpoint is able to successfully participate in transfers from and to other endpoints. Globus maintains two test endpoints, go#ep1 and go#ep2

**Comment by danpowers** [comment]
>I think probably "Globus Tutorial Endpoint 1" and "Globus Tutorial Endpoint 2"

Agree.
