### ISSUE TITLE
globus-connect-server-installation-guide - WC

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#94]
First sentence in Appendix C is a bit clunky...

Now:   The Globus team is improving the Globus Connect Server software all the time, occasionally, you should update your software to get all the latest bug fixes and improvements.

Suggest:  The Globus team is continuously improving the Globus Connect Server Software.  Update your software periodically to get all the latest bug fixes and improvements.   Do THIS (Not sure what THIS is... will ask Vas and edit later) to receive notification of critical updates.

**Comment by danpowers** [comment]
>Do THIS (Not sure what THIS is... will ask Vas and edit later) to receive notification of critical updates.

Not sure about the above. Is the "THIS" a link to some blog post or something?

The instructions in Appendix C don't notify the user of updates, they apply them.

**Comment by ruthaydt** [comment]
Dan, in response to your question about "THIS" - I put "THIS" in the issue as a placeholder to come back and fill in later after I heard back from Vas about the current method for announcing releases/updates -- when I was last with the group there was no separate 'admin' list.    From his email I see lots of progress has been made in the communication channel area -- cool!       You are correct that the Appendix is about how to update, and I do understand that.  Was thinking it might also be a good place to tell admins how to get notifications.   Have change my mind after your feedback & will suggest something different in next comment.

**Comment by ruthaydt** [comment]
New suggestion:  

- Cut first sentence in Appendix C as it's really about 'how to' update, not 'why to' update.
"The Globus team is improving the Globus Connect Server software all the time, occasionally, you should update your software to get all the latest bug fixes and improvements."

- Modify section 3.4 to add a new sentence at the end (proposed new sentence shown in italics):

3.4. Update Globus Endpoint
The set of software components that make up Globus Connect Server are improved and released on an ongoing basis. To take advantage of the lastest features we encourage you to update your local installation from the Globus repository regularly. The steps for doing an update are found here.  _We recommend that click here (Add a link to https://www.globus.org/mailing-lists ) and subscribe to the Admin mailing list to receive Globus Connect Server release notes._

It seems the "click here" is consistent with the phrasing used in other parts of the manual - if there is something better, that's fine with me.   The point is to try and encourage admins to subscribe to get the release notes... they may not read all the way to section 7.2.2
