### ISSUE TITLE
GCS install guide - sharing scenario question

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#99]
I really like the scenario in the sharing section, but ran into a question.        

The story is set up in 8.4 with "To illustrate let’s consider a case in which Adam, who is employed by ABC University and is the admin of the abcu#ep1 endpoint, wants to enable sharing on his endpoint for some of his users - such as Bob, Sue, etc. - so as to allow them to share with their collaborators (e.g. Ann) who do not have local accounts. In this case, Adam has decided that he wants to allow users to share out of the "globus" directory in their home directory and nowhere else."

I expected to see something in 8.5.1 that restricted the allowable shared paths to ~/globus, but I didn't.  Is that accomplished somewhere else, or didn't Adam really enforce that restriction?

**Comment by danpowers** [comment]
Yeah, that is missing. Something like this should be added to the end of 8.5.1:

In our scenario, Adam wants to allow his users to create shares that point to the 'globus' directory in their home directory. Adam has also decided that he wants to allow his users to create shares that can both be read and written to, so he will specify the SharingRestrictPaths option in his endpoint's globus-connect-server.conf file like so:

```SharingRestrictPaths = RW~/globus```

**Comment by ruthaydt** [comment]
Thanks for the answer Dan.  I'll change label and assign to Teresa.
